"use client";
import { useState } from "react";
import Image from "next/image";
import { TRADES, STATES, CITIES, getJobTypes, getChecklist } from "./data/permits";

type Screen = "form" | "results";

function printOrDownload(mode: "print" | "download", trade: string, job: string, state: string, city: string, safetyAlerts: any[], permits: any[]) {
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>PermitPro — ${trade} ${job}</title>
<style>
  body { font-family: Arial, sans-serif; background: #fff; color: #000; padding: 40px; max-width: 800px; margin: 0 auto; }
  .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #FDB913; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 28px; font-weight: 900; letter-spacing: 0.05em; }
  .logo span { color: #FDB913; }
  .meta { font-size: 13px; color: #666; }
  h2 { font-size: 14px; font-weight: 800; letter-spacing: 0.1em; text-transform: uppercase; color: #FDB913; border-bottom: 1px solid #eee; padding-bottom: 6px; margin: 24px 0 12px; }
  .alert { border-left: 3px solid #cc3333; padding: 8px 12px; margin-bottom: 8px; background: #fafafa; }
  .alert.warn { border-left-color: #888; }
  .alert-title { font-weight: 700; font-size: 13px; color: #cc3333; }
  .alert.warn .alert-title { color: #333; }
  .alert-desc { font-size: 12px; color: #555; margin-top: 3px; }
  .permit { border: 1px solid #ddd; border-radius: 4px; padding: 10px 14px; margin-bottom: 8px; }
  .permit-name { font-weight: 700; font-size: 14px; }
  .permit-dept { font-size: 12px; color: #FDB913; font-weight: 700; margin-top: 2px; }
  .permit-desc { font-size: 12px; color: #555; margin-top: 4px; }
  .permit-footer { display: flex; gap: 20px; margin-top: 6px; font-size: 12px; color: #333; }
  .permit-phone { font-weight: 700; }
  .footer { margin-top: 40px; border-top: 1px solid #eee; padding-top: 12px; font-size: 11px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="header">
  <div class="logo">PERMIT<span>PRO</span></div>
  <div class="meta">
    <div style="font-weight:700;font-size:15px;">${trade} — ${job}</div>
    ${city || state ? `<div>${[city, state].filter(Boolean).join(", ")}</div>` : ""}
    <div>Generated: ${new Date().toLocaleDateString()}</div>
  </div>
</div>

${safetyAlerts.length > 0 ? `
<h2>Safety Alerts</h2>
${safetyAlerts.map(a => `
<div class="alert ${a.isCritical ? "" : "warn"}">
  <div class="alert-title">${a.title}</div>
  <div class="alert-desc">${a.description}</div>
</div>`).join("")}` : ""}

<h2>Permits Required</h2>
${permits.map(p => `
<div class="permit">
  <div class="permit-name">${p.permitName}</div>
  <div class="permit-dept">${p.department} Dept.</div>
  ${p.description ? `<div class="permit-desc">${p.description}</div>` : ""}
  <div class="permit-footer">
    ${p.phone ? `<span class="permit-phone">📞 ${p.phone}</span>` : ""}
    <span>Est. ${p.estimatedDays} days</span>
  </div>
</div>`).join("")}

<div class="footer">Generated by PermitPro — permitpro-brown.vercel.app — Always verify with local authorities before starting work.</div>
</body>
</html>`;

  if (mode === "print") {
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 500);
  } else {
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `permitpro-${trade.toLowerCase().replace(/\s+/g,"-")}-${job.toLowerCase().replace(/\s+/g,"-")}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}

export default function Home() {
  const [screen, setScreen] = useState<Screen>("form");
  const [trade, setTrade] = useState("");
  const [job, setJob] = useState("");
  const [state, setState] = useState("");
  const [city, setCity] = useState("");
  const [checked, setChecked] = useState<Set<string>>(new Set());

  const jobTypes = trade ? getJobTypes(trade) : [];
  const cities = state ? (CITIES[state] || []) : [];
  const canGenerate = trade && job;
  const checklist = screen === "results" ? getChecklist(trade, job, state, city) : null;

  function generate() { setChecked(new Set()); setScreen("results"); }
  function reset() { setScreen("form"); setTrade(""); setJob(""); setState(""); setCity(""); setChecked(new Set()); }
  function toggleCheck(id: string) {
    setChecked(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; });
  }

  return (
    <>
      <style>{`
        .pp-wrap { width: 100%; min-height: 100vh; padding-bottom: 40px; }
        .pp-header { background: #000; padding: 16px 40px 12px; border-bottom: 1px solid #222; position: sticky; top: 0; z-index: 10; }
        .pp-form { padding: 40px; display: grid; gap: 24px; align-items: start; grid-template-columns: 1fr; }
        .pp-results { padding: 40px; display: grid; gap: 24px; align-items: start; grid-template-columns: 1fr; }
        @media (min-width: 768px) {
          .pp-form { grid-template-columns: repeat(2, 1fr); }
          .pp-results { grid-template-columns: repeat(2, 1fr); }
        }
        @media (min-width: 1100px) {
          .pp-form { grid-template-columns: repeat(3, 1fr); max-width: 1200px; margin: 0 auto; }
          .pp-results { grid-template-columns: repeat(3, 1fr); max-width: 1200px; margin: 0 auto; }
          .pp-header-inner { max-width: 1200px; margin: 0 auto; }
        }
        .btn-icon { background: #111; border: 1px solid #333; color: #fff; border-radius: 6px; padding: 10px 18px; font-size: 13px; font-weight: 700; cursor: pointer; letter-spacing: 0.04em; display: inline-flex; align-items: center; gap: 8px; transition: border-color 0.15s; }
        .btn-icon:hover { border-color: #FDB913; color: #FDB913; }
      `}</style>
      <div className="pp-wrap">
        <div className="pp-header">
          <div className="pp-header-inner">
            <Image src="/logo.png" alt="PermitPro" width={180} height={45} style={{ objectFit: "contain" }} priority />
          </div>
        </div>

        {screen === "form" ? (
          <div className="pp-form">
            <div>
              <span className="label">Trade Type</span>
              <div style={{ position: "relative" }}>
                <select value={trade} onChange={e => { setTrade(e.target.value); setJob(""); }}>
                  <option value="">Select trade...</option>
                  {TRADES.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
                <span style={{ position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", color: "#FDB913", pointerEvents: "none" }}>▼</span>
              </div>
            </div>

            <div>
              <span className="label">Job Type</span>
              <div style={{ position: "relative" }}>
                <select value={job} onChange={e => setJob(e.target.value)} disabled={!trade}>
                  <option value="">Select job...</option>
                  {jobTypes.map(j => <option key={j} value={j}>{j}</option>)}
                </select>
                <span style={{ position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", color: "#FDB913", pointerEvents: "none" }}>▼</span>
              </div>
            </div>

            <div>
              <span className="label">State</span>
              <div style={{ position: "relative" }}>
                <select value={state} onChange={e => { setState(e.target.value); setCity(""); }}>
                  <option value="">Select state...</option>
                  {STATES.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
                <span style={{ position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", color: "#FDB913", pointerEvents: "none" }}>▼</span>
              </div>
            </div>

            {state && (
              <div>
                <span className="label">City / Town</span>
                <div style={{ position: "relative" }}>
                  <select value={city} onChange={e => setCity(e.target.value)}>
                    <option value="">Select city...</option>
                    {cities.map(c => <option key={c} value={c}>{c}</option>)}
                  </select>
                  <span style={{ position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", color: "#FDB913", pointerEvents: "none" }}>▼</span>
                </div>
              </div>
            )}

            <button className="btn-gold" onClick={generate} disabled={!canGenerate} style={{ marginTop: 8, alignSelf: "end" }}>
              Generate Checklist
            </button>
          </div>

        ) : (
          <div className="pp-results">
            <div style={{ background: "#111", borderRadius: 8, padding: "14px 16px", borderLeft: "3px solid #FDB913" }}>
              <div style={{ fontSize: 13, fontWeight: 800, letterSpacing: "0.05em", color: "#FDB913" }}>{trade} — {job}</div>
              {(state || city) && <div style={{ fontSize: 12, color: "#999", marginTop: 4 }}>{[city, state].filter(Boolean).join(", ")}</div>}
            </div>

            {checklist && checklist.safetyAlerts.length > 0 && (
              <div>
                <span className="label">Safety Alerts</span>
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  {checklist.safetyAlerts.map((alert, i) => {
                    const id = `alert-${i}`;
                    const isChecked = checked.has(id);
                    return (
                      <div key={id} className="card" onClick={() => toggleCheck(id)}
                        style={{ display: "flex", gap: 12, alignItems: "flex-start", cursor: "pointer", opacity: isChecked ? 0.45 : 1, borderLeft: alert.isCritical ? "3px solid #FF6B6B" : "none" }}>
                        <span style={{ fontSize: 18, color: "#FDB913", flexShrink: 0, marginTop: 1 }}>{isChecked ? "☑" : "☐"}</span>
                        <div>
                          <div style={{ fontSize: 13, fontWeight: 700, color: alert.isCritical ? "#FF6B6B" : "#fff" }}>{alert.title}</div>
                          <div style={{ fontSize: 12, color: "#ccc", marginTop: 3 }}>{alert.description}</div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            <div>
              <span className="label">Permits Required</span>
              {checklist && checklist.permits.length > 0 ? (
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  {checklist.permits.map((permit, i) => {
                    const id = `permit-${i}`;
                    const isChecked = checked.has(id);
                    return (
                      <div key={id} className="card" onClick={() => toggleCheck(id)}
                        style={{ cursor: "pointer", opacity: isChecked ? 0.45 : 1 }}>
                        <div style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
                          <span style={{ fontSize: 18, color: "#FDB913", flexShrink: 0 }}>{isChecked ? "☑" : "☐"}</span>
                          <div style={{ flex: 1 }}>
                            <div style={{ fontSize: 14, fontWeight: 700 }}>{permit.permitName}</div>
                            <div style={{ fontSize: 12, color: "#FDB913", marginTop: 2 }}>{permit.department} Dept.</div>
                            {permit.description && <div style={{ fontSize: 12, color: "#ccc", marginTop: 4 }}>{permit.description}</div>}
                            <div style={{ display: "flex", alignItems: "center", gap: 12, marginTop: 8 }}>
                              {permit.phone && (
                                <a href={`tel:${permit.phone.replace(/\D/g,"")}`}
                                  style={{ fontSize: 12, fontWeight: 700, color: "#FDB913", textDecoration: "none" }}
                                  onClick={e => e.stopPropagation()}>
                                  📞 {permit.phone}
                                </a>
                              )}
                              <span style={{ fontSize: 12, color: "#888" }}>Est. {permit.estimatedDays} days</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="card" style={{ color: "#888", fontSize: 13 }}>No permits required for this job type.</div>
              )}
            </div>

            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button className="btn-icon" onClick={() => checklist && printOrDownload("print", trade, job, state, city, checklist.safetyAlerts, checklist.permits)}>
                🖨 Print
              </button>
              <button className="btn-icon" onClick={() => checklist && printOrDownload("download", trade, job, state, city, checklist.safetyAlerts, checklist.permits)}>
                ⬇ Download
              </button>
              <button onClick={reset} style={{ background: "transparent", border: "1px solid #333", color: "#fff", borderRadius: 6, padding: "10px 18px", fontSize: 13, fontWeight: 700, cursor: "pointer", letterSpacing: "0.05em", textTransform: "uppercase" }}>
                ← New Search
              </button>
            </div>
          </div>
        )}
      </div>
    </>
  );
}